import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import AppWrapper from "@/components/app-wrapper";
import "./globals.css";
import { Toaster } from "sonner";

const chakraPetch = Chakra_Petch({
  variable: "--font-body",
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chakraPetch.variable} antialiased`}
      >
        <Toaster />
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
